### PR TITLE
expose sqs metrics

### PR DESCRIPTION
**Pull request by maurolipp**
I've created a Dead Letter Queue so I want to create alerts when something is added to this Queue (using ApproximateNumberOfMessagesVisible) and I also want to check if there is a delay on processing messages on my input queues (using ApproximateAgeOfOldestMessage)

### CODE REVIEW

**Comment by harmw** [comment]
are there more metrics around SQS we would like to add? these two seem fine, but if there is more let's see which ones are valuable :)

**Comment by maurolipp** [comment]
> are there more metrics around SQS we would like to add? these two seem fine, but if there is more let's see which ones are valuable :)

There are more indeed:

- ApproximateNumberOfMessagesDelayed
- ApproximateNumberOfMessagesNotVisible
- NumberOfEmptyReceives
- NumberOfMessagesDeleted
- NumberOfMessagesReceived
- NumberOfMessagesSent
- SentMessageSize

My idea was to add only the ones I'll be using, since I understood that we have to pay for extracting those metrics.

**Comment by harmw** [comment]
depending on how costly that would get, I'm fine with adding them as they can help a great deal when diagnosing issues and what not 👍

**Comment by maurolipp** [comment]
> depending on how costly that would get, I'm fine with adding them as they can help a great deal when diagnosing issues and what not 👍

ok, then I think `ApproximateNumberOfMessagesNotVisible`, `ApproximateNumberOfMessagesDelayed`, `NumberOfMessagesDeleted`, `NumberOfMessagesReceived`, `NumberOfMessagesSent` could be useful.

I'll add them as well

**Review by harmw — APPROVED** [review]
lgtm

**Pull request merged**
