### PR TITLE
Update config-rest.yml

### PR DESCRIPTION
**Pull request by S1llyGit**
WHD-1258

### CODE REVIEW

**Comment by S1llyGit** [comment]
atlantis plan

**Comment by johnkeates** [comment]
I'm not sure if this belongs here in the base repository, perhaps something for the individual configuration in its runtime environment.

**Comment by kduvekot-wehkamp-nl** [comment]
😁

**Comment by kduvekot-wehkamp-nl** [comment]
@johnkeates there is a duplication between config-rest.yml and config-dms.yml .. resulting in the same DMS metric being exported twice  .. this pull request is to fix that

**Comment by johnkeates** [comment]
I just noticed, so hence the re-open 😄

**Comment by kduvekot-wehkamp-nl** [comment]
@HarryKroes / @jvdmeulen92  .. do you want to review this also?

**Review by jvdmeulen92 — APPROVED** [review]
lgtm

**Pull request merged**
